CREATE TABLE "TB_PRD" (
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"PRD_NM"	VARCHAR2(128)		NOT NULL,
	"CD_CTG"	CHAR(2)		NOT NULL,
	"PRICE_COST"	NUMBER(10)		NOT NULL,
	"COUNT_STOCK"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NOT NULL,
	"CD_STATE_PRD"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_PRD"."SEQ_PRD" IS '상품일련번호';

COMMENT ON COLUMN "TB_PRD"."PRD_NM" IS '상품명';

COMMENT ON COLUMN "TB_PRD"."CD_CTG" IS '상품 카테고리:1x(강아지),2x(고양이),3x(햄스터),4x(파충류)';

COMMENT ON COLUMN "TB_PRD"."PRICE_COST" IS '상품 원가';

COMMENT ON COLUMN "TB_PRD"."COUNT_STOCK" IS '상품 재고';

COMMENT ON COLUMN "TB_PRD"."FLG_DELETE" IS '삭제 여부';

COMMENT ON COLUMN "TB_PRD"."CD_STATE_PRD" IS '판매상품상태 코드:대기(0),승인(1),중지(2),반려(3),품절(9)';

COMMENT ON COLUMN "TB_PRD"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_PRD"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_PRD"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_PRD"."UPDATER" IS '수정자';