DROP TABLE "TB_MBR_MST";

CREATE TABLE "TB_MBR_MST" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"PASSWD"	VARCHAR2(64)		NOT NULL,
	"NICKNAME"	VARCHAR2(64)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"FLG_PETS"	CHAR(1)		NOT NULL,
	"PETS"	CHAR(16)		NULL,
	"EMAIL"	VARCHAR2(64)		NOT NULL,
	"MBR_NM"	VARCHAR2(64)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"PHONE"	VARCHAR2(64)		NOT NULL,
	"LAST_IP"	VARCHAR2(16)		NULL,
	"LAST_DT"	DATE		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MBR_MST"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_MBR_MST"."ID" IS '아이디';

COMMENT ON COLUMN "TB_MBR_MST"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MBR_MST"."NICKNAME" IS '닉네임';

COMMENT ON COLUMN "TB_MBR_MST"."CD_STATE" IS '상태코드:대기(0),정상(1),탈퇴(8),강퇴(9)';

COMMENT ON COLUMN "TB_MBR_MST"."FLG_PETS" IS '반려동물 여부';

COMMENT ON COLUMN "TB_MBR_MST"."PETS" IS '반려동물(예:YYYYY)';

COMMENT ON COLUMN "TB_MBR_MST"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MBR_MST"."MBR_NM" IS '성명';

COMMENT ON COLUMN "TB_MBR_MST"."GENDER" IS '성별:남자(M),여자(F)';

COMMENT ON COLUMN "TB_MBR_MST"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_MBR_MST"."LAST_IP" IS '마지막 로그인 IP';

COMMENT ON COLUMN "TB_MBR_MST"."LAST_DT" IS '마지막 로그인 일시';

COMMENT ON COLUMN "TB_MBR_MST"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_MBR_MST"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MBR_MST"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MBR_MST"."UPDATER" IS '수정자';

DROP TABLE "TB_BUY_MST";

CREATE TABLE "TB_BUY_MST" (
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"BUY_INFO"	VARCHAR2(128)		NOT NULL,
	"BUY_COUNT"	NUMBER(3)		NOT NULL,
	"BUY_PRICE"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"CD_STATE_PAY"	CHAR(1)		NULL,
	"CD_STATE_DELIVERY"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_INFO" IS '구매상품정보(예: 퓨리나 인도어 캣사료)';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_COUNT" IS '구매 상품 총 갯수';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_PRICE" IS '구매 상품 총 금액';

COMMENT ON COLUMN "TB_BUY_MST"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_PAY" IS '결제상태코드: 결제전(NULL), 성공(Y), 실패(N), 취소(C)';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_DELIVERY" IS '배송상태코드: 등록시(NULL), 확인중(C), 배송 준비중(P), 배송 중(D), 배송 완료(Y)';

COMMENT ON COLUMN "TB_BUY_MST"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BUY_MST"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BUY_MST"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_BUY_MST"."UPDATER" IS '수정자';

DROP TABLE "TB_MNG";

CREATE TABLE "TB_MNG" (
	"SEQ_MNG"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"PASSWD"	VARCHAR2(32)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"MNG_NM"	VARCHAR2(32)		NOT NULL,
	"EMAIL"	VARCHAR2(32)		NOT NULL,
	"PHONE"	VARCHAR2(16)		NOT NULL,
	"POST"	VARCHAR2(8)		NULL,
	"ADDR1"	VARCHAR2(128)		NULL,
	"ADDR2"	VARCHAR2(128)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL,
	"NICKNAME"	VARCHAR2(32)		NOT NULL
);

COMMENT ON COLUMN "TB_MNG"."SEQ_MNG" IS '관리자 일련번호';

COMMENT ON COLUMN "TB_MNG"."ID" IS '아이디';

COMMENT ON COLUMN "TB_MNG"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MNG"."CD_STATE" IS '상태코드: 대기(0), 성공(1), 반려(2), 탈퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_MNG"."MNG_NM" IS '성명';

COMMENT ON COLUMN "TB_MNG"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MNG"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_MNG"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MNG"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MNG"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MNG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_MNG"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MNG"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MNG"."UPDATER" IS '수정자';

COMMENT ON COLUMN "TB_MNG"."NICKNAME" IS '닉네임';

DROP TABLE "TB_PRD";

CREATE TABLE "TB_PRD" (
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"PRD_NM"	VARCHAR2(128)		NOT NULL,
	"PET_ITEMS"	NUMBER(3)		NOT NULL,
	"SPECIES"	NUMBER(3)		NOT NULL,
	"PRICE_COST"	NUMBER(10)		NOT NULL,
	"COUNT_STOCK"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NOT NULL,
	"CD_STATE_PRD"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_PRD"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_PRD"."PRD_NM" IS '상품명';

COMMENT ON COLUMN "TB_PRD"."PET_ITEMS" IS '판매 상품 카테고리 : 사료(x1), 간식(x2), 하우스(x3), 기타(x4)';

COMMENT ON COLUMN "TB_PRD"."SPECIES" IS '동물 종류: 강아지(1),고양이(2),햄스터(3),파충류(4),물고기(5)';

COMMENT ON COLUMN "TB_PRD"."PRICE_COST" IS '상품 원가';

COMMENT ON COLUMN "TB_PRD"."COUNT_STOCK" IS '상품 재고';

COMMENT ON COLUMN "TB_PRD"."FLG_DELETE" IS '삭제 여부';

COMMENT ON COLUMN "TB_PRD"."CD_STATE_PRD" IS '판매상품상태코드: 대기(0), 승인(1), 중지(2),반려(3), 재고소진(9)';

COMMENT ON COLUMN "TB_PRD"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_PRD"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_PRD"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_PRD"."UPDATER" IS '수정자';

DROP TABLE "TB_SLE";

CREATE TABLE "TB_SLE" (
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"DESCES"	VARCHAR2(2048)		NOT NULL,
	"IMG"	VARCHAR2(1024)		NULL,
	"DESCES_IMG"	VARCHAR2(3072)		NULL,
	"CD_CTG_PET"	NUMBER(3)		NULL,
	"SPECIES"	NUMBER(3)		NOT NULL,
	"PET_ITEMS"	NUMBER(3)		NOT NULL,
	"PRICE_SALE"	NUMBER(10)		NOT NULL,
	"CD_STATE_SALE"	CHAR(1)		NOT NULL,
	"DT_SALE_START"	DATE		NOT NULL,
	"DT_SALE_END"	DATE		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_SLE"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_SLE"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_SLE"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_SLE"."DESCES" IS '판매 상품 설명';

COMMENT ON COLUMN "TB_SLE"."IMG" IS '이미지(대표)';

COMMENT ON COLUMN "TB_SLE"."DESCES_IMG" IS '판매 상품 상세 이미지';

COMMENT ON COLUMN "TB_SLE"."CD_CTG_PET" IS '페이지 카테고리:강아지(1),고양이(2),햄스터(3),파충류(4),물고기(5)';

COMMENT ON COLUMN "TB_SLE"."SPECIES" IS '동물 종류: 강아지(1),고양이(2),햄스터(3),파충류(4),물고기(5)';

COMMENT ON COLUMN "TB_SLE"."PET_ITEMS" IS '판매 상품 카테고리 : 사료(x1), 간식(x2), 하우스(x3), 기타(x4)';

COMMENT ON COLUMN "TB_SLE"."PRICE_SALE" IS '판매가격';

COMMENT ON COLUMN "TB_SLE"."CD_STATE_SALE" IS '판매상품상태코드: 대기(0), 승인(1),중지(2), 반려(3), 품절(9)';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_START" IS '판매 시작 일시';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_END" IS '판매 종료 일시';

COMMENT ON COLUMN "TB_SLE"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_SLE"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_SLE"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_SLE"."UPDATER" IS '수정자';

DROP TABLE "TB_BUY_DTL";

CREATE TABLE "TB_BUY_DTL" (
	"SEQ_BUY_DTL"	NUMBER(19)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"CD_STATE_BUY"	CHAR(1)		NULL
);

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_DTL" IS '구매 상세 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_MST" IS '구매  마스터 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."COUNT" IS '판매 상품 개수';

COMMENT ON COLUMN "TB_BUY_DTL"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BUY_DTL"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BUY_DTL"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BUY_DTL"."CD_STATE_BUY" IS '주문상태코드 : 주문전(NULL), 주문확정(Y) 주문취소(C) 주문교환(E) 주문환불(R)';

DROP TABLE "TB_PAY";

CREATE TABLE "TB_PAY" (
	"SEQ_PAY"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"CD_PG"	NUMBER(3)		NOT NULL,
	"NUM_ORDER"	VARCHAR2(64)		NOT NULL,
	"NUM_DEAL"	VARCHAR2(64)		NOT NULL,
	"CD_RESPONSE"	VARCHAR2(8)		NULL,
	"CD_PAY_METHOD"	NUMBER(3)		NOT NULL,
	"FLG_SUCCESS"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(3)		NOT NULL
);

COMMENT ON COLUMN "TB_PAY"."SEQ_PAY" IS '결제 일련변호';

COMMENT ON COLUMN "TB_PAY"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_PAY"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_PAY"."CD_PG" IS 'PG사 코드: 페이업(1)';

COMMENT ON COLUMN "TB_PAY"."NUM_ORDER" IS '주문 번호';

COMMENT ON COLUMN "TB_PAY"."NUM_DEAL" IS '거래(트랜잭션)번호';

COMMENT ON COLUMN "TB_PAY"."CD_RESPONSE" IS '응답코드';

COMMENT ON COLUMN "TB_PAY"."CD_PAY_METHOD" IS '결제수단 코드(예: 카드,이체 등)';

COMMENT ON COLUMN "TB_PAY"."FLG_SUCCESS" IS '성공여부: 기본(NULL),  성공(Y), 실패(N)';

COMMENT ON COLUMN "TB_PAY"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_PAY"."REGISTER" IS '등록자';

DROP TABLE "TB_BBS";

CREATE TABLE "TB_BBS" (
	"SEQ_BBS"	NUMBER(10)		NOT NULL,
	"SEQ_BBS_PARENT"	NUMBER(10)		NULL,
	"CD_BBS_TYPE"	NUMBER(3)		NULL,
	"TITLE"	VARCHAR2(256)		NOT NULL,
	"CD_CTG"	NUMBER(3)		NOT NULL,
	"CD_CTG_PET"	NUMBER(3)		NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FLG_TOP"	CHAR(1)		NULL,
	"FLG_REPLY"	CHAR(1)		NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"READED"	NUMBER(10)		NULL,
	"FILE_SAVE"	VARCHAR2(256)		NULL,
	"FILE_ORIG"	VARCHAR2(64)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL,
	"TAG"	VARCHAR2(256)		NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NULL,
	"NICKNAME"	VARCHAR2(256)		NULL
);

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS" IS '게시판 일련번호';

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS_PARENT" IS '게시판 상위일련번호';

COMMENT ON COLUMN "TB_BBS"."CD_BBS_TYPE" IS '게시판타입코드:공지사항(1),FAQ(2),문의(3),입양(4),커뮤니티(전체글)(5)인기글(6),자유게시판(7),Q&A(8),입양후기(9),정보글(11),기타(12)';

COMMENT ON COLUMN "TB_BBS"."TITLE" IS '제목';

COMMENT ON COLUMN "TB_BBS"."CD_CTG" IS '카테고리:가입 및 탈퇴(1),입양(2),구매(3),결제(4),배송(5),환불(6),커뮤니티(8),기타(9)';

COMMENT ON COLUMN "TB_BBS"."CD_CTG_PET" IS '카테고리 코드:강아지(1),고양이(2),햄스터(3),파충류(4),기타(5)';

COMMENT ON COLUMN "TB_BBS"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_BBS"."FLG_TOP" IS '최상위여부(공지사항,인기글 등)';

COMMENT ON COLUMN "TB_BBS"."FLG_REPLY" IS '답변여부';

COMMENT ON COLUMN "TB_BBS"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BBS"."READED" IS '조회수';

COMMENT ON COLUMN "TB_BBS"."FILE_SAVE" IS '파일 저장명(경로포함)';

COMMENT ON COLUMN "TB_BBS"."FILE_ORIG" IS '파일 원본명';

COMMENT ON COLUMN "TB_BBS"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BBS"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BBS"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_BBS"."UPDATER" IS '수정자';

COMMENT ON COLUMN "TB_BBS"."TAG" IS '태그';

COMMENT ON COLUMN "TB_BBS"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_BBS"."SEQ_SLE" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BBS"."NICKNAME" IS '닉네임';

DROP TABLE "TB_MBR_DTL";

CREATE TABLE "TB_MBR_DTL" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"POST"	VARCHAR2(32)		NOT NULL,
	"ADDR1"	VARCHAR2(256)		NOT NULL,
	"ADDR2"	VARCHAR2(256)		NOT NULL,
	"FLG_SMS"	CHAR(1)		NOT NULL,
	"DT_SMS"	DATE		NOT NULL,
	"FLG_EMAIL"	CHAR(1)		NOT NULL,
	"DT_EMAIL"	DATE		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MBR_DTL"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_MBR_DTL"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MBR_DTL"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MBR_DTL"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MBR_DTL"."FLG_SMS" IS '수신여부SMS';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_SMS" IS '수신여부_SMS 일시';

COMMENT ON COLUMN "TB_MBR_DTL"."FLG_EMAIL" IS '수신여부EMAIL';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_EMAIL" IS '수신여부EMAIL일시';

COMMENT ON COLUMN "TB_MBR_DTL"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_MBR_DTL"."UPDATER" IS '수정자';

DROP TABLE "TB_TRM_AGR";

CREATE TABLE "TB_TRM_AGR" (
	"SEQ_TRM_AGR"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_TRM"	NUMBER(3)		NOT NULL,
	"FLG_AGR"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM_AGR" IS '약관동의일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM" IS '약관 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."FLG_AGR" IS '수락여부';

COMMENT ON COLUMN "TB_TRM_AGR"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_TRM_AGR"."REGISTER" IS '등록자';

DROP TABLE "TB_STAT_MBR";

CREATE TABLE "TB_STAT_MBR" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"POST"	VARCHAR2(5)		NOT NULL,
	"DT_REG"	DATE		NOT NULL
);

COMMENT ON COLUMN "TB_STAT_MBR"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_STAT_MBR"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_STAT_MBR"."DT_REG" IS '등록일시';

DROP TABLE "TB_BSK";

CREATE TABLE "TB_BSK" (
	"SEQ_BSK"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_PRD"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"DT_UPT"	DATE		NULL
);

COMMENT ON COLUMN "TB_BSK"."SEQ_BSK" IS '장바구니 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BSK"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_BSK"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BSK"."COUNT" IS '구매수량';

COMMENT ON COLUMN "TB_BSK"."IMG" IS '판매상품이미지';

COMMENT ON COLUMN "TB_BSK"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_BSK"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_BSK"."DT_UPT" IS '수정일시';

DROP TABLE "TB_SLE_IMG";

CREATE TABLE "TB_SLE_IMG" (
	"SEQ_SLE_IMG"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE_IMG" IS '판매 상품 이미지 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_SLE_IMG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_SLE_IMG"."REGISTER" IS '등록자';

DROP TABLE "TB_DNT";

CREATE TABLE "TB_DNT" (
	"SEQ_DNT"	NUMBER(10)		NOT NULL,
	"SEQ_TRM_AGR"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"DNT_PRICE"	NUMBER(10)		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_REG"	DATE		NULL
);

COMMENT ON COLUMN "TB_DNT"."SEQ_DNT" IS '후원 일련번호';

COMMENT ON COLUMN "TB_DNT"."SEQ_TRM_AGR" IS '약관동의일련번호';

COMMENT ON COLUMN "TB_DNT"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_DNT"."DNT_PRICE" IS '기부금액';

COMMENT ON COLUMN "TB_DNT"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_DNT"."DT_REG" IS '등록일시';

DROP TABLE "TB_ADT";

CREATE TABLE "TB_ADT" (
	"SEQ_ADT"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"DESCES"	VARCHAR2(2048)		NOT NULL,
	"IMG"	VARCHAR2(256)		NULL,
	"CD_STATE_SALE"	CHAR(3)		NOT NULL,
	"DT_SALE_START"	DATE		NOT NULL,
	"DT_SALE_END"	DATE		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_ADT"."SEQ_ADT" IS '입양공고 일련번호';

COMMENT ON COLUMN "TB_ADT"."SLE_NM" IS '입양공고 제목';

COMMENT ON COLUMN "TB_ADT"."DESCES" IS '설명';

COMMENT ON COLUMN "TB_ADT"."IMG" IS '이미지(대표)';

COMMENT ON COLUMN "TB_ADT"."CD_STATE_SALE" IS '판매상품상태코드: 대기(0), 승인(1),중지(2), 반려(3), 완료(9)';

COMMENT ON COLUMN "TB_ADT"."DT_SALE_START" IS '공고 시작 일시';

COMMENT ON COLUMN "TB_ADT"."DT_SALE_END" IS '공고 종료 일시';

COMMENT ON COLUMN "TB_ADT"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_ADT"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_ADT"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_ADT"."UPDATER" IS '수정자';

DROP TABLE "TB_ADT_IMG";

CREATE TABLE "TB_ADT_IMG" (
	"SEQ_ADT_IMG"	NUMBER(10)		NOT NULL,
	"SEQ_ADT"	NUMBER(10)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_ADT_IMG"."SEQ_ADT_IMG" IS '입양 공고 이미지 일련번호';

COMMENT ON COLUMN "TB_ADT_IMG"."SEQ_ADT" IS '입양 공고 일련번호';

COMMENT ON COLUMN "TB_ADT_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_ADT_IMG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_ADT_IMG"."REGISTER" IS '등록자';

DROP TABLE "TB_STAT_BUY";

CREATE TABLE "TB_STAT_BUY" (
	"SEQ_BUY_DTL"	NUMBER(19)		NOT NULL,
	"CD_STATE_BUY"	CHAR(1)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"BUY_PRICE"	NUMBER(10)		NOT NULL,
	"PRICE"	NUMBER(10)		NULL,
	"DT_REG"	DATE		NOT NULL
);

COMMENT ON COLUMN "TB_STAT_BUY"."SEQ_BUY_DTL" IS '구매 상세 일련번호';

COMMENT ON COLUMN "TB_STAT_BUY"."CD_STATE_BUY" IS '주문상태코드 : 주문전(NULL), 주문확정(Y) 주문취소(C) 주문교환(E) 주문환불(R)';

COMMENT ON COLUMN "TB_STAT_BUY"."COUNT" IS '판매 상품 총개수';

COMMENT ON COLUMN "TB_STAT_BUY"."BUY_PRICE" IS '구매 총 금액';

COMMENT ON COLUMN "TB_STAT_BUY"."PRICE" IS '판매상품가격';

COMMENT ON COLUMN "TB_STAT_BUY"."DT_REG" IS '등록일(주문일자)';

DROP TABLE "TB_POP_POSTS";

CREATE TABLE "TB_POP_POSTS" (
	"SEQ_POP_POSTS"	NUMBER(10)		NOT NULL,
	"SEQ_LKE"	NUMBER(10)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_BBS"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_POP_POSTS"."SEQ_POP_POSTS" IS '인기글 일련번호';

COMMENT ON COLUMN "TB_POP_POSTS"."SEQ_LKE" IS '좋아요 일련번호';

COMMENT ON COLUMN "TB_POP_POSTS"."SEQ_MBR" IS '회원일련번호';

COMMENT ON COLUMN "TB_POP_POSTS"."SEQ_BBS" IS '게시판 일련번호';

DROP TABLE "TB_RDD";

CREATE TABLE "TB_RDD" (
	"SEQ_RDD"	NUMBER(10)		NOT NULL,
	"SEQ_FBS"	NUMBER(10)		NOT NULL,
	"DT_REG_RDD"	DATE		NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_RDD"."SEQ_RDD" IS '조회기록 일련번호';

COMMENT ON COLUMN "TB_RDD"."SEQ_FBS" IS '자유게시판 일련번호';

COMMENT ON COLUMN "TB_RDD"."DT_REG_RDD" IS '조회한일시';

COMMENT ON COLUMN "TB_RDD"."REGISTER" IS '등록자';

DROP TABLE "TB_STAT_RDD";

CREATE TABLE "TB_STAT_RDD" (
	"SEQ_FBS"	NUMBER(10)		NOT NULL,
	"SEQ_RDD"	NUMBER(10)		NOT NULL,
	"DT_REG_RDD"	DATE		NULL
);

COMMENT ON COLUMN "TB_STAT_RDD"."SEQ_FBS" IS '자유게시판 일련번호';

COMMENT ON COLUMN "TB_STAT_RDD"."SEQ_RDD" IS '조회기록 일련번호';

COMMENT ON COLUMN "TB_STAT_RDD"."DT_REG_RDD" IS '등록일시';

DROP TABLE "TB_FBS";

CREATE TABLE "TB_FBS" (
	"SEQ_FBS"	NUMBER(10)		NOT NULL,
	"SEQ_FBS_PARENT"	NUMBER(10)		NULL,
	"CD_FBS_TYPE"	NUMBER(3)		NULL,
	"TITLE"	VARCHAR2(256)		NOT NULL,
	"CD_CTG_PET"	NUMBER(3)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FLG_TOP"	CHAR(1)		NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"READED"	NUMBER(10)		NULL,
	"FILE_SAVE"	VARCHAR2(256)		NULL,
	"FILE_ORIG"	VARCHAR2(64)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_FBS"."SEQ_FBS" IS '자유게시판 일련번호';

COMMENT ON COLUMN "TB_FBS"."SEQ_FBS_PARENT" IS '자유게시판 상위일련번호';

COMMENT ON COLUMN "TB_FBS"."CD_FBS_TYPE" IS '자유게시판타입코드: 자유게시판(1),QnA(2),입양후기(3),정보글(4)';

COMMENT ON COLUMN "TB_FBS"."TITLE" IS '제목';

COMMENT ON COLUMN "TB_FBS"."CD_CTG_PET" IS '동물카테고리: 강아지(1), 고양이(2), 햄스터(3), 파충류(4), 기타(5)';

COMMENT ON COLUMN "TB_FBS"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_FBS"."FLG_TOP" IS '최상위여부(인기글)';

COMMENT ON COLUMN "TB_FBS"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_FBS"."READED" IS '조회수';

COMMENT ON COLUMN "TB_FBS"."FILE_SAVE" IS '파일저장명(경로포함)';

COMMENT ON COLUMN "TB_FBS"."FILE_ORIG" IS '파일원본명';

COMMENT ON COLUMN "TB_FBS"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_FBS"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_FBS"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_FBS"."UPDATER" IS '수정자';

DROP TABLE "TB_LKE";

CREATE TABLE "TB_LKE" (
	"SEQ_LKE"	NUMBER(10)		NOT NULL,
	"FLG_LKE"	CHAR(1)		NOT NULL,
	"CD_CTG"	NUMBER(3)		NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_REG"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL,
	"DT_UPT"	DATE		NULL,
	"SEQ_BBS"	NUMBER(10)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_LKE"."SEQ_LKE" IS '좋아요 일련번호';

COMMENT ON COLUMN "TB_LKE"."FLG_LKE" IS '좋아요 여부';

COMMENT ON COLUMN "TB_LKE"."CD_CTG" IS '카테고리:상품(0),입양(1),게시글(2),댓글(3)';

COMMENT ON COLUMN "TB_LKE"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_LKE"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_LKE"."UPDATER" IS '수정자';

COMMENT ON COLUMN "TB_LKE"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_LKE"."SEQ_BBS" IS '게시판 일련번호';

COMMENT ON COLUMN "TB_LKE"."SEQ_MBR" IS '회원일련번호';

DROP TABLE "TB_CMT";

CREATE TABLE "TB_CMT" (
	"SEQ_COMMENT"	NUMBER(10)		NOT NULL,
	"SEQ_COMMENT_PARENT"	NUMBER(10)		NULL,
	"CONTENT"	VARCHAR2(256)		NULL,
	"FLG_REPLY"	CHAR(1)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"SEQ_BBS"	NUMBER(10)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"NICKNAME"	VARCHAR2(256)		NULL
);

COMMENT ON COLUMN "TB_CMT"."SEQ_COMMENT" IS '댓글 일련번호';

COMMENT ON COLUMN "TB_CMT"."SEQ_COMMENT_PARENT" IS '상위댓글 일련번호';

COMMENT ON COLUMN "TB_CMT"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_CMT"."FLG_REPLY" IS '답변여부';

COMMENT ON COLUMN "TB_CMT"."FLG_DELETE" IS '삭제여부';

COMMENT ON COLUMN "TB_CMT"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_CMT"."SEQ_BBS" IS '게시판일련번호';

COMMENT ON COLUMN "TB_CMT"."SEQ_MBR" IS '댓글을 작성한 회원 일련번호';

COMMENT ON COLUMN "TB_CMT"."DT_UPT" IS '수정일시';

COMMENT ON COLUMN "TB_CMT"."NICKNAME" IS '닉네임';

ALTER TABLE "TB_MBR_MST" ADD CONSTRAINT "PK_TB_MBR_MST" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_BUY_MST" ADD CONSTRAINT "PK_TB_BUY_MST" PRIMARY KEY (
	"SEQ_BUY_MST"
);

ALTER TABLE "TB_MNG" ADD CONSTRAINT "PK_TB_MNG" PRIMARY KEY (
	"SEQ_MNG"
);

ALTER TABLE "TB_PRD" ADD CONSTRAINT "PK_TB_PRD" PRIMARY KEY (
	"SEQ_PRD"
);

ALTER TABLE "TB_SLE" ADD CONSTRAINT "PK_TB_SLE" PRIMARY KEY (
	"SEQ_SLE"
);

ALTER TABLE "TB_BUY_DTL" ADD CONSTRAINT "PK_TB_BUY_DTL" PRIMARY KEY (
	"SEQ_BUY_DTL"
);

ALTER TABLE "TB_PAY" ADD CONSTRAINT "PK_TB_PAY" PRIMARY KEY (
	"SEQ_PAY"
);

ALTER TABLE "TB_BBS" ADD CONSTRAINT "PK_TB_BBS" PRIMARY KEY (
	"SEQ_BBS"
);

ALTER TABLE "TB_MBR_DTL" ADD CONSTRAINT "PK_TB_MBR_DTL" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_TRM_AGR" ADD CONSTRAINT "PK_TB_TRM_AGR" PRIMARY KEY (
	"SEQ_TRM_AGR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "PK_TB_STAT_MBR" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_BSK" ADD CONSTRAINT "PK_TB_BSK" PRIMARY KEY (
	"SEQ_BSK"
);

ALTER TABLE "TB_SLE_IMG" ADD CONSTRAINT "PK_TB_SLE_IMG" PRIMARY KEY (
	"SEQ_SLE_IMG"
);

ALTER TABLE "TB_DNT" ADD CONSTRAINT "PK_TB_DNT" PRIMARY KEY (
	"SEQ_DNT"
);

ALTER TABLE "TB_ADT" ADD CONSTRAINT "PK_TB_ADT" PRIMARY KEY (
	"SEQ_ADT"
);

ALTER TABLE "TB_ADT_IMG" ADD CONSTRAINT "PK_TB_ADT_IMG" PRIMARY KEY (
	"SEQ_ADT_IMG"
);

ALTER TABLE "TB_POP_POSTS" ADD CONSTRAINT "PK_TB_POP_POSTS" PRIMARY KEY (
	"SEQ_POP_POSTS"
);

ALTER TABLE "TB_RDD" ADD CONSTRAINT "PK_TB_RDD" PRIMARY KEY (
	"SEQ_RDD"
);

ALTER TABLE "TB_FBS" ADD CONSTRAINT "PK_TB_FBS" PRIMARY KEY (
	"SEQ_FBS"
);

ALTER TABLE "TB_LKE" ADD CONSTRAINT "PK_TB_LKE" PRIMARY KEY (
	"SEQ_LKE"
);

ALTER TABLE "TB_CMT" ADD CONSTRAINT "PK_TB_CMT" PRIMARY KEY (
	"SEQ_COMMENT"
);

ALTER TABLE "TB_MBR_DTL" ADD CONSTRAINT "FK_TB_MBR_MST_TO_TB_MBR_DTL_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR_MST" (
	"SEQ_MBR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "FK_TB_MBR_MST_TO_TB_STAT_MBR_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR_MST" (
	"SEQ_MBR"
);

